import solfeggio

tonalnost=solfeggio.tonality()


print(tonalnost.C_dur())
print(tonalnost.a_moll())
print(tonalnost.G_dur())
print(tonalnost.e_moll())
print(tonalnost.D_dur())
print(tonalnost.h_moll())
print(tonalnost.A_dur())
print(tonalnost.fis_moll())
print(tonalnost.E_dur())
print(tonalnost.cis_moll())
print(tonalnost.H_dur())
print(tonalnost.gis_moll())
print(tonalnost.Fis_dur())
print(tonalnost.dis_moll())
print(tonalnost.Cis_dur())
print(tonalnost.ais_moll())

print(tonalnost.F_dur())
print(tonalnost.d_moll())
print(tonalnost.B_dur())
print(tonalnost.g_moll())
print(tonalnost.Es_dur())
print(tonalnost.c_moll())
print(tonalnost.As_dur())
print(tonalnost.f_moll())
print(tonalnost.Des_dur())
print(tonalnost.b_moll())
print(tonalnost.Ges_dur())
print(tonalnost.es_moll())
print(tonalnost.Ces_dur())
print(tonalnost.as_moll())
